export const courseData = [
  {
    id: 1,
    imageName: "course_ui_ux_design.jpg",
    title: "UI/UX Design Fundamentals",
    description:
      "Learn the core principles of user interface and user experience design, from wireframes to high-fidelity prototypes.",
    instructor: "Sarah Mitchell",
    category: "Design",
    price: "Free",
    rating: 4.8,
    students: "12.4k",
    duration: "6h 30m",
    buttonText: "Enroll Now",
  },
  {
    id: 2,
    imageName: "course_react_native.jpg",
    title: "React Native for Beginners",
    description:
      "Build cross-platform mobile apps from scratch using React Native, covering navigation, state, and APIs.",
    instructor: "James Carter",
    category: "Development",
    price: "$49.99",
    rating: 4.6,
    students: "8.9k",
    duration: "10h 15m",
    buttonText: "Buy Course",
  },
  {
    id: 3,
    imageName: "course_digital_marketing.jpg",
    title: "Digital Marketing Essentials",
    description:
      "Master SEO, social media marketing, and paid advertising strategies to grow any brand online.",
    instructor: "Priya Nair",
    category: "Marketing",
    price: "Free",
    rating: 4.5,
    students: "15.2k",
    duration: "5h 45m",
    buttonText: "Enroll Now",
  },
  {
    id: 4,
    imageName: "course_python_data_science.jpg",
    title: "Python for Data Science",
    description:
      "Analyze real-world datasets using Python, Pandas, and visualization libraries like Matplotlib.",
    instructor: "Daniel Osei",
    category: "Data Science",
    price: "$59.99",
    rating: 4.9,
    students: "20.1k",
    duration: "12h 00m",
    buttonText: "Buy Course",
  },
  {
    id: 5,
    imageName: "course_photography_basics.jpg",
    title: "Photography Basics",
    description:
      "Understand camera settings, lighting, and composition to capture stunning photos.",
    instructor: "Elena Vargas",
    category: "Photography",
    price: "Free",
    rating: 4.4,
    students: "6.7k",
    duration: "4h 20m",
    buttonText: "Enroll Now",
  },
  {
    id: 6,
    imageName: "course_business_finance.jpg",
    title: "Business Finance 101",
    description:
      "Get a practical introduction to budgeting, forecasting, and financial statements for entrepreneurs.",
    instructor: "Michael Chen",
    category: "Business",
    price: "$39.99",
    rating: 4.3,
    students: "5.3k",
    duration: "7h 10m",
    buttonText: "Buy Course",
  },
  {
    id: 7,
    imageName: "course_graphic_design.jpg",
    title: "Graphic Design with Figma",
    description:
      "Create logos, posters, and social media graphics using industry-standard Figma tools.",
    instructor: "Aisha Bello",
    category: "Design",
    price: "Free",
    rating: 4.7,
    students: "9.8k",
    duration: "6h 00m",
    buttonText: "Enroll Now",
  },
  {
    id: 8,
    imageName: "course_web_development.jpg",
    title: "Full-Stack Web Development",
    description:
      "Build complete web applications using HTML, CSS, JavaScript, Node.js, and MongoDB.",
    instructor: "Tom Richards",
    category: "Development",
    price: "$79.99",
    rating: 4.9,
    students: "22.6k",
    duration: "18h 45m",
    buttonText: "Buy Course",
  },
  {
    id: 9,
    imageName: "course_public_speaking.jpg",
    title: "Public Speaking Mastery",
    description:
      "Overcome stage fright and deliver confident, persuasive presentations in any setting.",
    instructor: "Rachel Adams",
    category: "Personal Development",
    price: "Free",
    rating: 4.6,
    students: "7.1k",
    duration: "3h 50m",
    buttonText: "Enroll Now",
  },
  {
    id: 10,
    imageName: "course_machine_learning.jpg",
    title: "Machine Learning A-Z",
    description:
      "Dive into supervised and unsupervised learning algorithms with hands-on Python projects.",
    instructor: "Kevin Park",
    category: "Data Science",
    price: "$69.99",
    rating: 4.8,
    students: "18.3k",
    duration: "14h 30m",
    buttonText: "Buy Course",
  },
];
