type Question = {
  id: number;
  title: string;
  description: string;
  tech: string[];
  difficulty: "Easy" | "Medium" | "Hard";
  companies: string[];
  time: number;
  completed: boolean;
};
export const mockData: Question[] = [
  {
    id: 17,
    title: "Stopwatch with Laps",
    description: "Build a stopwatch with lap recording feature",
    tech: ["React.js", "JavaScript"],
    difficulty: "Medium",
    companies: ["Startups"],
    time: 30,
    completed: false,
  },
  {
    id: 18,
    title: "Flatten Nested Array",
    description: "Write a function to flatten deeply nested arrays",
    tech: ["JavaScript"],
    difficulty: "Easy",
    companies: ["Google", "Amazon"],
    time: 15,
    completed: false,
  },
  {
    id: 19,
    title: "Drag and Drop Kanban Board",
    description: "Build a Trello-like drag and drop board",
    tech: ["React.js", "JavaScript"],
    difficulty: "Hard",
    companies: ["Atlassian", "Microsoft"],
    time: 90,
    completed: false,
  },
  {
    id: 20,
    title: "Deep Clone an Object",
    description: "Implement a deep clone function without libraries",
    tech: ["JavaScript"],
    difficulty: "Medium",
    companies: ["Facebook", "Uber"],
    time: 20,
    completed: false,
  },
  {
    id: 21,
    title: "Star Rating Component",
    description: "Create an interactive star rating widget",
    tech: ["React.js"],
    difficulty: "Easy",
    companies: ["Amazon", "Flipkart"],
    time: 20,
    completed: false,
  },
  {
    id: 22,
    title: "Custom Event Emitter",
    description: "Build an EventEmitter class with on/off/emit methods",
    tech: ["JavaScript"],
    difficulty: "Medium",
    companies: ["Netflix", "Uber"],
    time: 25,
    completed: false,
  },
  {
    id: 23,
    title: "Nested Comment System",
    description: "Build a Reddit-style nested comments UI",
    tech: ["React.js", "JavaScript"],
    difficulty: "Hard",
    companies: ["Reddit", "Facebook"],
    time: 60,
    completed: false,
  },
  {
    id: 24,
    title: "Throttle Function",
    description: "Implement a throttle utility from scratch",
    tech: ["JavaScript"],
    difficulty: "Medium",
    companies: ["Google", "Microsoft"],
    time: 20,
    completed: false,
  },
  {
    id: 25,
    title: "Multi-Step Form Wizard",
    description: "Create a form with multiple steps and validation",
    tech: ["React.js", "JavaScript"],
    difficulty: "Medium",
    companies: ["Airbnb", "Stripe"],
    time: 45,
    completed: false,
  },
  {
    id: 26,
    title: "Promise.all Polyfill",
    description: "Implement your own version of Promise.all",
    tech: ["JavaScript"],
    difficulty: "Hard",
    companies: ["Google", "Amazon"],
    time: 30,
    completed: false,
  },
  {
    id: 27,
    title: "Dark Mode Toggle",
    description: "Implement theme switching with persisted preference",
    tech: ["React.js"],
    difficulty: "Easy",
    companies: ["Startups"],
    time: 15,
    completed: false,
  },
  {
    id: 28,
    title: "Typeahead / Autocomplete",
    description: "Build an autocomplete search input with suggestions",
    tech: ["React.js", "JavaScript"],
    difficulty: "Medium",
    companies: ["Google", "Airbnb"],
    time: 35,
    completed: false,
  },
  {
    id: 29,
    title: "Currying Function",
    description: "Implement a curry function for any arity",
    tech: ["JavaScript"],
    difficulty: "Hard",
    companies: ["Facebook", "Uber"],
    time: 25,
    completed: false,
  },
  {
    id: 30,
    title: "Modal Dialog Component",
    description: "Build a reusable, accessible modal component",
    tech: ["React.js", "JavaScript"],
    difficulty: "Easy",
    companies: ["Amazon", "Microsoft"],
    time: 20,
    completed: false,
  },
  {
    id: 31,
    title: "LRU Cache Implementation",
    description: "Implement a Least Recently Used cache",
    tech: ["JavaScript"],
    difficulty: "Hard",
    companies: ["Google", "Amazon", "Microsoft"],
    time: 40,
    completed: false,
  },
  {
    id: 32,
    title: "Form Builder with Dynamic Fields",
    description: "Create a form where fields can be added/removed dynamically",
    tech: ["React.js"],
    difficulty: "Medium",
    companies: ["Salesforce", "Startups"],
    time: 40,
    completed: false,
  },
  {
    id: 33,
    title: "Memoize Function",
    description: "Write a generic memoization higher-order function",
    tech: ["JavaScript"],
    difficulty: "Medium",
    companies: ["Facebook", "Netflix"],
    time: 20,
    completed: false,
  },
  {
    id: 34,
    title: "Notification Toast System",
    description: "Build a toast notification system with auto-dismiss",
    tech: ["React.js", "JavaScript"],
    difficulty: "Medium",
    companies: ["Slack", "Startups"],
    time: 30,
    completed: false,
  },
  {
    id: 35,
    title: "Virtualized List Rendering",
    description: "Render large lists efficiently using windowing technique",
    tech: ["React.js", "JavaScript"],
    difficulty: "Hard",
    companies: ["Facebook", "Twitter"],
    time: 60,
    completed: false,
  },
  {
    id: 36,
    title: "Custom useFetch Hook",
    description:
      "Build a reusable hook for data fetching with loading/error states",
    tech: ["React.js", "JavaScript"],
    difficulty: "Medium",
    companies: ["Startups", "Airbnb"],
    time: 30,
    completed: false,
  },
];
